DROP TABLE SEA_LEVEL;

CREATE TABLE SEA_LEVEL (
	Station_ID VARCHAR,
	YEAR INT,
	MONTH INT,
	Monthly_MSL DECIMAL(3,3),
	Linear_Trend DECIMAL(3,3),
	High_Conf DECIMAL(3,3),
	Low_Conf DECIMAL(3,3)
);

ALTER TABLE SEA_LEVEL 
	DROP COLUMN Linear_Trend,
	DROP COLUMN High_Conf,
	DROP COLUMN Low_Conf
;

DELETE FROM SEA_LEVEL
	WHERE YEAR < 1980

SELECT * FROM SEA_LEVEL
	
SELECT YEAR, ROUND(AVG(Monthly_MSL),3) AS YEARLY_MSL
FROM SEA_LEVEL
GROUP BY YEAR 
ORDER BY YEAR ASC
	
SELECT * FROM SEA_LEVEL